-- Create a new relational table with 3 columns

CREATE TABLE LECTURE 
(
      ID VARCHAR2(10) PRIMARY KEY,
      DIV NUMBER NOT NULL,
      COM VARCHAR2(20) NOT NULL,
      NAME VARCHAR2(30) NOT NULL,
      CREDIT NUMBER NOT NULL,
      ROOM VARCHAR2(20) NOT NULL,
      "YEAR" NUMBER NOT NULL,
      SEMESTER VARCHAR2(20) NOT NULL,
      COLLEGE VARCHAR2(30) NOT NULL,
      MAJOR VARCHAR2(30) NOT NULL,
      PROFESSOR VARCHAR2(10) NOT NULL,
      "LIMIT" NUMBER,
      "CURRENT" NUMBER NOT NULL
);

COMMIT;