-- Create a new relational table with 3 columns

CREATE TABLE STUDENT
(
	ID NUMBER PRIMARY KEY,
	NAME VARCHAR2(20) NOT NULL,
	COLLEGE VARCHAR2(30) NOT NULL,
	MAJOR VARCHAR2(30) NOT NULL,
	GRADE NUMBER NOT NULL,
	ENROLL NUMBER NOT NULL,
	CREDIT NUMBER NOT NULL,
	PW VARCHAR(20) NOT NULL
);


COMMIT;