-- Create a new relational table with 3 columns

CREATE TABLE PROFESSOR
(
	ID NUMBER PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL,
	COLLEGE VARCHAR(30) NOT NULL,
	MAJOR VARCHAR(30) NOT NULL,
	ENROLL NUMBER NOT NULL,
	PW VARCHAR(20) NOT NULL
);

COMMIT;