-- Create a new relational table with 3 columns

CREATE TABLE LECTURE 
(
      ID VARCHAR2(6),
      DIV NUMBER(2) NOT NULL,
      COM VARCHAR2(6) NOT NULL,
      NAME VARCHAR2(30) NOT NULL,
      CREDIT VARCHAR2(1) NOT NULL,
      ROOM VARCHAR2(5) NOT NULL,
      YEAR NUMBER(4) NOT NULL,
      SEMESTER VARCHAR2(20) NOT NULL,
      COLLEGE VARCHAR2(10) NOT NULL,
      MAJOR VARCHAR2(20) NOT NULL,
      PROFESSOR VARCHAR2(10) NOT NULL,
      LIMIT NUMBER(3) NOT NULL,
      CURRENT NUMBER(3) NOT NULL,

      CONSTANT PK_ID PRIMARY KEY(ID)
);

COMMIT;