-- Create a new relational table with 3 columns

CREATE TABLE STUDENT 
(
  ID NUMBER(10),
  NAME VARCHAR(20) NOT NULL,
  COLLEGE VARCHAR(20) NOT NULL,
  MAJOR VARCHAR(20) NOT NULL,
  GRADE NUMBER(1) NOT NULL,
  ENROLL NUMBER(4) NOT NULL,
  CREDIT NUMBER(2) NOT NULL,

  CONSTANT PK_ID PRIMARY KEY(ID)
);

COMMIT;