-- In addition to being able to group data using GROUP BY, SQL also allows you to filter which groups to include and which to exclude.
-- HAVING : This is very similar to WHERE. In fact, all types of WHERE clauses you learned about thus far can be used with HAVING.
-- When we want to limit the results of a query based on values of the individual rows, use WHERE.
-- When we want to limit the results of a query based on an aggregate property, use HAVING.
-- HAVING statement always comes after GROUP BY, but before ORDER BY and LIMIT.